### ISSUE TITLE
关于/Boot分区

### ISSUE THREAD

**Issue by xuehrs** [Karmenzind/dotfiles-and-scripts#1]
如果我不用/boot分区。只用/分区，安装完毕后。还能进入，你能做到吗？我的意思是，如果不破坏当前启动情况下，无论电脑是linux 还是windows，还是魔改的东西。你应该只需要提供相关的如何启动！（如果是全新硬盘，就别这样做了）
Fat分区专为启动工具使用，不用/boot能启动，可能会有各种不兼容问题。这个问题可以无视，因为你只需要看看启动arch正常不就可了。

**Comment by Karmenzind** [comment]
谢谢反馈。
可以做到。但是放开条件后可能的场景非常多，而且不易测试。我后面会加上针对MBR和复用现有启动分区的支持，满足常见且基础的场景。
我没有打算造轮子，写这个repo是一时兴起，作为快捷脚本，一切从简。现有的轮子已经非常强大，要追求兼容性，antergos和manjaro都可以满足你 ;-)

**Comment by xuehrs** [comment]
虽然`现有的工具支持这个功能。我不得不说，对于新人来说，这类问题还是无法解决。要精确的，很费事。要方便的，bug还不少。我这里是双硬盘，就遇到这样的情况。已经手动解决了
