### ISSUE TITLE
关于CycleModes()

### ISSUE THREAD

**Issue by yusihai719** [Karmenzind/dotfiles-and-scripts#2]

**Comment by yusihai719** [comment]
在VIM 的配置文件中有个调用CycleModes()函数 是切换主题的吧，不过没有这个函数体啊

**Comment by Karmenzind** [comment]
@yusihai719 你需要把主题设置成atomic才用得上它

**Comment by Karmenzind** [comment]
cyclemodes是atomic自带的

至于直接切换colorscheme
许多主题并没有考虑到在vim中通过colo直接切换的场景，颜色初始化和渲染会有问题
所以不建议在同一个vim session中去切换主题
